---
# Area
- name: area/github
  color: "72CCF3" # Light Blue
  description: >-
    Changes made to github actions

- name: area/pre-commit
  color: "BC9BE3" # Lavender
  description: >-
    Changes made to pre-commit hooks

- name: area/license
  color: "F4D1B7" # Peach
  description: >-
    Changes made to license file

- name: area/readme
  color: "84B6EB" # Steel Blue
  description: >-
    Changes made to README.md file

- name: area/changelogs
  color: "7BD7E0" # Turquoise
  description: >-
    Changes made to changelogs

- name: area/meta
  color: "FFB366" # Light Orange
  description: >-
    Changes made to meta files

- name: area/roles
  color: "FF6600" # Orange
  description: >-
    Changes made to Ansible roles

- name: area/playbooks
  color: "66CCFF" # Sky Blue
  description: >-
    Changes made to playbooks

- name: area/taskfiles
  color: "66CCFF" # Sky Blue
  description: >-
    Changes made to taskfiles

- name: area/galaxy
  color: "99CC00" # Lime Green
  description: >-
    Changes made to galaxy.yml

- name: area/ansible
  color: "FF99CC" # Pink
  description: >-
    Changes made to ansible configuration

# Individual Roles
- name: role/vulnerable_windows_scenarios
  color: "CC6699" # Dusty Rose
  description: >-
    Changes made to vulnerable_windows_scenarios role

# Individual Playbooks
- name: playbook/vulnerable_windows_scenarios
  color: "FF66CC" # Bright Pink
  description: >-
    Changes made to vulnerable windows scenarios playbook

# Renovate
- name: renovate/container
  color: "FFC300" # Golden Yellow
- name: renovate/github-action
  color: "FFD700" # Gold
- name: renovate/github-release
  color: "FFE4B5" # Moccasin

# Semantic Type
- name: type/digest
  color: "FFEC19" # Yellow
- name: type/patch
  color: "FF9800" # Dark Orange
- name: type/minor
  color: "FF6B6B" # Salmon
- name: type/major
  color: "F6412D" # Red Orange
- name: type/break
  color: "FF0000" # Bright Red

# Release Issue
- name: image-not-found
  color: "EE0701" # Error Red

# Uncategorized
- name: bug
  color: "D93F0B" # Dark Red
- name: do-not-merge
  color: "B60205" # Blood Red
- name: docs
  color: "0075CA" # Documentation Blue
- name: enhancement
  color: "A2EEEF" # Light Blue
