---
- name: Set DEBIAN_FRONTEND to noninteractive
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: 'DEBIAN_FRONTEND=noninteractive'
    create: true
    mode: '0644'
  become: true
  when: ansible_os_family == 'Debian'

- name: Install packages
  become: true
  ansible.builtin.package:
    name: "{{ package_management_install_packages }}"
    state: present
    update_cache: true
  when: ansible_os_family in ['Debian', 'RedHat']
  environment: "{{ (ansible_os_family == 'Debian') | ternary({'DEBIAN_FRONTEND': 'noninteractive'}, {}) }}"
  tags: packages
