---
namespace: l50
name: dumpsterfire
version: 0.0.1
readme: README.md
authors:
  - Jayson Grace <techvomit.net>
description: An intentionally vulnerable Ansible collection designed for cybersecurity education and infrastructure testing
license_file: "LICENSE"
tags: [bad_decision_making, dumpsterfire, security]
repository: https://github.com/l50/ansible-collection-dumpsterfire
issues: https://github.com/l50/ansible-collection-dumpsterfire/issues
