---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Include variables
      ansible.builtin.include_vars:
        file: "../../vars/main.yml"

    - name: Include default variables
      ansible.builtin.include_vars:
        file: "../../defaults/main.yml"

    - name: Include zsh_setup_get_enriched_users tasks
      ansible.builtin.include_tasks: ../../tasks/zsh_setup_get_enriched_users.yml

    - name: Ensure zsh_setup_enriched_users is a list
      ansible.builtin.set_fact:
        zsh_setup_enriched_users: "{{ zsh_setup_enriched_users | default([]) }}"

    # Confirm sudo configuration for Linux systems
    - name: Check if sudo is passwordless for current user
      ansible.builtin.command: "sudo -n true"
      register: sudo_check
      ignore_errors: true
      changed_when: false
      when: ansible_facts['os_family'] != 'Darwin'

    - name: Assert sudo is passwordless (Linux only)
      ansible.builtin.assert:
        that:
          - sudo_check.rc == 0
        msg: "Passwordless sudo is not configured for the current user"
      when: ansible_facts['os_family'] != 'Darwin'

    # Confirm that .oh-my-zsh directories exist for all users
    - name: Confirm per-user $HOME/.oh-my-zsh directories exist for all users
      ansible.builtin.stat:
        path: "{{ item.home }}/.oh-my-zsh"
      register: oh_my_zsh_test
      loop: "{{ zsh_setup_enriched_users }}"

    - name: Assert per-user $HOME/.oh-my-zsh directories
      ansible.builtin.assert:
        that:
          - "oh_my_zsh_test.results[item | int].stat.exists"
          - "oh_my_zsh_test.results[item | int].stat.mode == '0755'"
        msg: "$HOME/.oh-my-zsh directory check failed for {{ item.username }}"
      loop: "{{ zsh_setup_enriched_users }}"

    # Confirm that omz-installer.sh is removed for all zsh_setup_enriched_users
    - name: Confirm omz-installer.sh is removed for all zsh_setup_enriched_users
      ansible.builtin.stat:
        path: "{{ item.home }}/omz-installer.sh"
      register: zsh_installer_test
      loop: "{{ zsh_setup_enriched_users }}"

    - name: Assert omz-installer.sh removal
      ansible.builtin.assert:
        that:
          - "not zsh_installer_test.results[item | int].stat.exists"
        msg: "zsh-installer.sh removal check failed for {{ item.username }}"
      loop: "{{ zsh_setup_enriched_users }}"

    # Confirm that .zshrc files exist for all users
    - name: Confirm per-user $HOME/.zshrc files exist for all users
      ansible.builtin.stat:
        path: "{{ item.home }}/.zshrc"
      register: zshrc_test
      loop: "{{ zsh_setup_enriched_users }}"

    - name: Assert per-user $HOME/.zshrc files
      ansible.builtin.assert:
        that:
          - "zshrc_test.results[item | int].stat.exists"
          - "zshrc_test.results[item | int].stat.mode == '0644'"
        msg: "$HOME/.zshrc file check failed for {{ item.username }}"
      loop: "{{ zsh_setup_enriched_users }}"
