---
- name: Gather available local users
  ansible.builtin.getent:
    database: passwd
  register: getent_passwd
  when: ansible_os_family != 'Darwin'

- name: Gather available local users on macOS
  cowdogmoo.workstation.getent_passwd:
  register: getent_passwd
  when: ansible_os_family == 'Darwin'

- name: Update home for all users
  ansible.builtin.set_fact:
    zsh_setup_enriched_users: >-
      {{ (zsh_setup_enriched_users | default([])) |
      rejectattr('username', 'equalto', user.username) | list +
      [user | combine({
        'home': (ansible_facts.getent_passwd[user.username].home | default('/Users/' + user.username)) if ansible_os_family == 'Darwin' else (ansible_facts.getent_passwd[user.username].home | default('/home/' + user.username)),
        'shell': user.shell,
        'usergroup': user.usergroup,
        'username': user.username
      })] | selectattr('home', 'defined') | list }}
  loop: "{{ zsh_setup_users }}"
  loop_control:
    loop_var: user
