---
- name: Check if systemd is present
  ansible.builtin.command: systemctl --version
  ignore_errors: true
  register: systemd_check
  changed_when: false

- name: Set fact for systemd presence
  ansible.builtin.set_fact:
    is_systemd_present: "{{ systemd_check.rc == 0 }}"

- name: Get uids of {{ vnc_setup_users }}
  ansible.builtin.command: id -u {{ item.username }}
  loop: "{{ vnc_setup_users }}"
  check_mode: false
  changed_when: false
  register: uids
  when: is_systemd_present

- name: "Create uid_results from {{ uids.results }}"
  ansible.builtin.set_fact:
    uid_results: "{{ uid_results | default([]) + [item.stdout] }}"
  loop: "{{ uids.results }}"
  when: is_systemd_present

- name: "Merge uids into vnc_setup_users"
  cowdogmoo.workstation.merge_list_dicts_into_list:
    ls_dicts: "{{ vnc_setup_users }}"
    ls: "{{ uid_results }}"
  register: vnc_setup_users_uid
  when: is_systemd_present

- name: Ensure dbus service is running
  become: true
  ansible.builtin.service:
    name: dbus
    state: started
    enabled: true
  when: is_systemd_present

- name: Ensure user runtime directory exists
  become: true
  ansible.builtin.file:
    path: "/run/user/{{ item.uid }}"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
    mode: "0700"
  loop: "{{ vnc_setup_users_uid.result }}"
  when: is_systemd_present

- name: Enable persistent services for all users
  become: true
  ansible.builtin.command: loginctl enable-linger {{ item.username }}
  loop: "{{ vnc_setup_users }}"
  changed_when: false
  when: is_systemd_present

- name: Create systemd directories
  become: true
  ansible.builtin.file:
    path: "/home/{{ item.username }}/.config/systemd/user"
    state: directory
    mode: "0744"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
  loop: "{{ vnc_setup_users }}"
  when: is_systemd_present

- name: Check existence of per-user systemd service files
  become: true
  ansible.builtin.stat:
    path: "/home/{{ item.username }}/.config/systemd/user/vncserver.service"
  loop: "{{ vnc_setup_users }}"
  register: vncserver_service_check
  when: is_systemd_present

- name: Update per-user systemd service files
  become: true
  ansible.builtin.template:
    src: vncserver.j2
    dest: "/home/{{ item.username }}/.config/systemd/user/vncserver.service"
    mode: "0744"
    owner: "{{ item.username }}"
    group: "{{ item.usergroup | default(item.username) }}"
  loop: "{{ vnc_setup_users }}"
  when: is_systemd_present

- name: Set fact for vncserver service file existence
  ansible.builtin.set_fact:
    vncserver_service_exists: "{{ vncserver_service_check.results | map(attribute='stat.exists') | list }}"
  when: is_systemd_present

- name: Add start_vnc script to profile.d
  become: true
  ansible.builtin.template:
    src: start_vnc.sh.j2
    dest: "/etc/profile.d/start_vnc.sh"
    mode: "0755"
  when: is_systemd_present

- name: Create XDG_RUNTIME_DIR script in /etc/profile.d
  become: true
  ansible.builtin.copy:
    dest: /etc/profile.d/xdg_runtime_dir.sh
    content: |
      export XDG_RUNTIME_DIR="/run/user/$(id -u)"
    mode: "0755"
  when: is_systemd_present

- name: Check if VNC service is enabled and running
  become: true
  become_user: "{{ item.username }}"
  ansible.builtin.systemd:
    name: vncserver.service
    state: started
    enabled: true
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ item.uid }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ item.uid }}/bus"
  loop: "{{ vnc_setup_users_uid.result }}"
  ignore_errors: true
  register: vnc_service_status
  changed_when: false
  when: is_systemd_present

- name: "Enable VNC service for {{ vnc_setup_users_uid }}"
  become: true
  become_user: "{{ item.0.username }}"
  ansible.builtin.systemd:
    name: vncserver.service
    state: started
    enabled: true
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ item.0.uid }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ item.0.uid }}/bus"
  when: "'inactive' in (vnc_service_status.results | selectattr('item.username', 'equalto', item.0.username) | map(attribute='status.ActiveState') | first) and is_systemd_present"
  loop: "{{ vnc_setup_users_uid.result | zip(vncserver_service_exists) | list }}"
