---
asdf_version: "0.16.0"
asdf_username: "{{ ansible_user_id | default(ansible_user) }}"
asdf_usergroup: "{{ (ansible_facts['os_family'] == 'Darwin') | ternary('staff', asdf_username) }}"
asdf_user_home: "{{ (ansible_facts['os_family'] == 'Darwin') | ternary(ansible_env.HOME, '/home/' + asdf_username) }}"
asdf_dir: "{{ asdf_user_home }}/.asdf"
asdf_install_script_path: /tmp/setup_asdf_env
asdf_shells:
  - "/usr/bin/zsh"
  - "/bin/zsh"
  - "/usr/bin/bash"
  - "/bin/bash"
asdf_shell: "{{ '/bin/zsh' if ansible_distribution == 'MacOSX' else '/usr/bin/zsh' }}"
asdf_plugins:
  - name: golang
    version: "1.23.5"
    scope: "global"
  - name: python
    version: "3.13.1"
    scope: "global"
  - name: ruby
    version: "3.3.5"
    scope: "global"
  - name: helm
    version: "3.17.0"
    scope: "global"
  - name: kubectl
    version: "1.32.1"
    scope: "global"
  - name: packer
    version: "1.12.0"
    scope: "global"
