---
- name: Converge
  hosts: all
  gather_facts: true
  pre_tasks:
    - name: Create test user
      ansible.builtin.user:
        name: "{{ ansible_distribution | lower }}"
        shell: /bin/bash
        create_home: true
      become: true

    - name: Set ansible_user_id and home facts
      ansible.builtin.set_fact:
        ansible_user_id: "{{ ansible_distribution | lower }}"
        ansible_env:
          HOME: "/home/{{ ansible_distribution | lower }}"

    - name: Setup role paths for testing
      ansible.builtin.set_fact:
        ansible_roles_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../roles:{{ lookup('env', 'ANSIBLE_ROLES_PATH') | default('/etc/ansible/roles', true) }}"

- name: Run the workstation playbook
  ansible.builtin.import_playbook: ../../workstation.yml
  vars:
    asdf_username: "{{ ansible_distribution | lower }}"
