---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: docker

platforms:
  - name: ubuntu-workstation
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../../roles:${ANSIBLE_ROLES_PATH:-/etc/ansible/roles}"
    ANSIBLE_COLLECTIONS_PATH: "~/.ansible/collections"

  config_options:
    defaults:
      interpreter_python: auto_silent
      collections_paths: "~/.ansible/collections"

  inventory:
    links:
      hosts: inventory

  playbooks:
    converge: converge.yml

  ansible_args:
    - --connection=docker
    - -v

verifier:
  name: ansible
